### ISSUE TITLE
Request for date option

### ISSUE THREAD

**Issue by unsetglobbing** [yapkke/pdf-rename#1]
Thank you this is great. Would be perfect if the ModDate or CreationDate value could be used to extract a year...

**Comment by yapkke** [comment]
Pushed changes to do that.  You can extract either ModDate or CreationDate using the --mdate and --cdate options respectively.

**Comment by unsetglobbing** [comment]
Thank you - that makes the script very much more useful - however I was
hoping to end up with something like:

LastNameOfFirstAuthor_Title after removal of non-alphanumeric
characters_2012.pdf

Wit it be possible for you to support this by switches?

Regards,
Antony

**Comment by yapkke** [comment]
The use of underscore instead of comma to demarcate would be an easy fix but PDF metadata does not have the concept of first author, let alone last name of first author.

**Comment by unsetglobbing** [comment]
I was hoping that with suitable use of regular expressions it might be possible to determine the last name of the first author the majority of the time. 

Regards,
Antony

**Comment by yapkke** [comment]
Would you have a suggestion on the regular expression?  It seems like a hack to me.

**Comment by unsetglobbing** [comment]
Yes its quite a complex problem. How about the form Smith_A_D_Analytic
solutions to the wave equation_1923.pdf

The first authors name shouldn't be too hard to extract as there are only
three cases, 1. one author, 2. two authors and 3. more that two authors.
The name would be terminated by a ".", "and" or "&", and "," respectively.

**Comment by yapkke** [comment]
Sorry, this is too much of a hack for me.

**Comment by unsetglobbing** [comment]
Understood. Clean code is nice, it's just that you can't always get what has to be done done with clean code...

Antony
