### ISSUE TITLE
module location

### ISSUE THREAD

**Issue by rvelseg** [yapkke/pdf-rename#2]
Hi, thanks for the code, it is just what I was looking for. 

Since, in order to use the scripts as regular commands of CLI, I did symlinks for the callable scripts

```
ln -s ~/somepath/pdf-rename/bin/* ~/bin/
```

I struggled a little importing the module, I was getting the error 

```
ImportError: No module named pdfrename.pdftk
```

After a few trial and error I did a symlink like the following

```
ln -s ~/somepath/pdf-rename/pdfrename/ ~/.local/lib/python2.7/site-packages/
```

Then

```
ls -lha .local/lib/python2.7/site-packages/pdfrename
lrwxrwxrwx 1 username username 43 Mar 11 16:24 .local/lib/python2.7/site-packages/pdfrename -> /home/username/somepath/pdf-rename/pdfrename
```

I chose this directory because I see it's the place where `pip install --user package` deploys its modules. If you have a better idea please tell me.

**Comment by yapkke** [comment]
You can update your PATH and PYTHONPATH environment variables to solve the respective issues.  Yeah, I could probably create a package for this but this is some environment and deployment tool specific.  Good luck with the tool.

**Comment by rvelseg** [comment]
Thank you :)
